# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - curl -sL https://sentry.io/get-cli/ | bash
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - export commithash=$(git rev-parse HEAD)
      - sed -i "s~legalatoms-ui@\${packageInfo.version}~$commithash~g" note.txt
      - cat note.txt
      # - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - ./sentry.sh
      - ./rollbar.sh

# Include only the files required for your application to run.
artifacts:
  files:
    - package.json
    - .env
    - dist/**/*
    - .npmrc