# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - curl -sL https://sentry.io/get-cli/ | bash
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - export VERSION=$(sentry-cli releases propose-version)
      - echo Sentry Proposed Version ${VERSION}
      - sentry-cli releases new -p $SENTRY_PROJECT $VERSION
      - sentry-cli releases set-commits --auto --ignore-missing $VERSION
      - echo Sentry Release ${VERSION}

# Include only the files required for your application to run.
artifacts:
  files:
    - package.json
    - .env
    - dist/**/*
    - .npmrc