# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy Otp Service

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ./src/otp-service --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/otp-service -c Release -o ${{env.DOTNET_ROOT}}/otpDeploy

      - name: Generate deployment package
        run: 7z a deploy.zip ${{env.DOTNET_ROOT}}/otpDeploy aws-windows-deployment-manifest.json

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v19
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.APPLICATION_NAME }}
          environment_name: ${{ secrets.ENVIRONMENT_NAME }}
          version_label: ${{ github.sha }}
          region: us-east-2
          deployment_package: deploy.zip
          existing_bucket_name: ${{ secrets.BUCKET_NAME }}