# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Compile TypeScript
      run: npm run build

    - name: Generate deployment package
      run: zip -r deploy.zip package.json package-lock.json dist .npmrc

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v19
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.APPLICATION_NAME }}
        environment_name: ${{ secrets.ENVIRONMENT_NAME }}
        version_label: ${{ github.sha }}
        region: us-east-2
        deployment_package: deploy.zip
        existing_bucket_name: ${{ secrets.BUCKET_NAME }}